# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EagleChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EagleChat

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

pod 'GoogleSignIn'

pod 'MessageKit'
pod 'JGProgressHUD'
pod 'SDWebImage'

  target 'EagleChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EagleChatUITests' do
    # Pods for testing
  end

end
